"""empty message

Revision ID: ee651b4c4469
Revises: 1ad4bb8df822
Create Date: 2018-08-08 10:39:04.428106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee651b4c4469'
down_revision = '1ad4bb8df822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titile', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ships',
    sa.Column('user.id', sa.Integer(), nullable=True),
    sa.Column('article.id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article.id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['user.id'], ['user.id'], )
    )
    op.add_column('comment', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'article', ['article_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'article_id')
    op.drop_table('ships')
    op.drop_table('article')
    # ### end Alembic commands ###
